# fly.toml file generated for eskridge on 2022-09-02T17:07:31-05:00

app          = "eskridge"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[build]
  image = "ghost:5-alpine"

[env]
  database__client               = "mysql"
  database__connection__database = "ghost"
  database__connection__host     = "eskridge-db.internal"
  database__connection__user     = "ghost_user"
  mail__options__host            = "smtp.postmarkapp.com"
  mail__options__port            = "587"
  mail__options__service         = "Postmark"
  mail__transport                = "SMTP"
  url                            = "https://eskridge.dev"

[mount]
  destination = "/var/lib/ghost/content"
  source      = "eskridge_ghost_data"

[experimental]
  allowed_public_ports = []
  auto_rollback        = true

[[services]]
  http_checks   = []
  internal_port = 2368
  processes     = ["app"]
  protocol      = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type       = "connections"

  [[services.ports]]
    force_https = true
    handlers    = ["http"]
    port        = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443

  [[services.tcp_checks]]
    grace_period  = "1s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "2s"
